FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# GBG Identity API's
Integrate with GBG quickly with mocked data.

## AuthenticationService [/authenticate/v1/connect/token]
Calls for using GBG Authorisation services in conjunction with your SSO service.

### Get Token [GET]
This service will accept the authorisation code from your SSO provider and exchange it for a GBG access token
    
+ Request (application/x-www-form-urlencoded)
            
        {
            "client_id": "Included for completeness, may be used in future for a second factor authentication. Should be set to 'ro.client'",
            "grant_type": "Use the custom grant type 'id_auth'",
            "client_secret": "Included for completeness, may be used in future for a second factor authentication. Should be set to 'secret'.",
            "scope": "One or more registered scopes as a space separated list. If not specified, a token for all explicitly allowed scopes will be issued.",
            "id_token": "a JSON web token that has been obtained from an external authentication provider"
        }

+ Response 200 (application/json)

        {
            "access_token": "9CMEo0Ty1QQmNibTNzc05KbnQ2OVJxbDdORi1vTVUiLCJ0eXAiOiJKV1QifQ.eyJuYmYiOjE1ODE1NDY",
            "expires_in": 3600,
            "token_type": "Bearer"
        }
        
+ Response 400 (application/json)

        {
            "error": [
                "unsupported_grant_type",
                "invalid_client"
            ]
        }   

+ Response 500 (application/json)
    
        {
            "error": "server_error"
        }

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }